export const options = [
  { name: "Antenna design", id: 1 },
  { name: "App development", id: 2 },
  { name: "Big Data", id: 3 },
  { name: "Biomedicine", id: 4 },
  { name: "Blockchain Technology", id: 5 },
  { name: "Bluetooth", id: 6 },
  { name: "Chatbot", id: 7 },
  { name: "Circuits & Systems", id: 55 },
  { name: "Cloud computing", id: 8 },
  { name: "Competitive programming", id: 56 },
  { name: "Computer vision", id: 9 },
  { name: "Controls and Systems", id: 10 },
  { name: "Consulting", id: 57 },
  { name: "Cyber Security", id: 43 },
  { name: "Data Science", id: 49 },
  { name: "Data Visualisation", id: 11 },
  { name: "Design Thinking", id: 47 },
  { name: "Digital circuits", id: 12 },
  { name: "Digital Forensics", id: 44 },
  { name: "Disentangled Representations", id: 13 },
  { name: "Drone", id: 14 },
  { name: "Electromagnetics", id: 15 },
  { name: "Embedded Systems", id: 16 },
  { name: "Entrepreneurship", id: 52 },
  { name: "Enterprise Network Design", id: 48 },
  { name: "Ethical hacking", id: 17 },
  { name: "Finance Management", id: 53 },
  { name: "Game UX design", id: 18 },
  { name: "Game Theory", id: 46 },
  { name: "Game development", id: 19 },
  { name: "Image processing", id: 20 },
  { name: "Internet of Things", id: 21 },
  { name: "Linux", id: 22 },
  { name: "Machine learning", id: 23 },
  { name: "Marketing", id: 50 },
  { name: "Microcontroller", id: 24 },
  { name: "Microprocessor", id: 25 },
  { name: "Microwave Engineering", id: 42 },
  { name: "MySQL", id: 26 },
  { name: "Natural Language Processing", id: 27 },
  { name: "Network design/troubleshooting", id: 28 },
  { name: "NoSQL", id: 29 },
  { name: "PLC", id: 30 },
  { name: "Power Electronics", id: 31 },
  { name: "Probabilistic theory", id: 32 },
  { name: "Reinforcement learning", id: 33 },
  { name: "Robotics", id: 34 },
  { name: "Sales", id: 51 },
  { name: "Security testing", id: 35 },
  { name: "Signal processing", id: 36 },
  { name: "Software development", id: 37 },
  { name: "Statistical computation", id: 38 },
  { name: "Stock Trading", id: 54 },
  { name: "VLSI", id: 39 },
  { name: "Web development", id: 40 },
  { name: "Network Management", id: 45 },
];

