export const SUCCESS = "SUCCESS";
export const FAILED = "FAILED";
export const LOADING = "LOADING";

// Sign_in
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

// logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const SET_SOCKET_SUCCESS = "SET_SOCKET_SUCCESS";

// // Get all teachers
// export const GET_TEACHERS_FAILED = "GET_TEACHERS_FAILED";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
// export const SUCCESS_STUDENT_LIST = "SUCCESS_STUDENT_LIST"
// export const SUCCESS_TEACHER_LIST = "SUCCESS_TEACHER_LIST"

export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_CHANNELS_FAILED = "GET_CHANNELS_FAILED";
export const GET_CHANNELS_SUCCESS = "GET_CHANNELS_SUCCESS";
export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";
